---
# we use docker as plateform
driver:
  name: docker
  privileged: true
  volume: /sys/fs/cgroup:/sys/fs/cgroup

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

platforms:
  # Centos
  - name: centos-7-ansible
    driver:
      image: diodonfrost/centos-7-ansible
      run_command: /sbin/init
      platform: centos
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
  - name: centos-6-ansible
    driver:
      image: diodonfrost/centos-6-ansible
      platform: centos
      run_command: /sbin/init
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

  # Fedora
  - name: fedora-27-ansible
    driver:
      image: diodonfrost/fedora-27-ansible
      run_command: /usr/sbin/init
      platform: centos
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
  - name: fedora-26-ansible
    driver:
      image: diodonfrost/fedora-26-ansible
      run_command: /usr/sbin/init
      platform: centos
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config

  # Ubuntu
  - name: ubuntu-18.04-ansible
    driver:
      provision_command: apt-get install -y init
      run_command: /sbin/init
      platform: ubuntu
  - name: ubuntu-17.10-ansible
    driver:
      provision_command: apt-get install -y init
      run_command: /sbin/init
      platform: ubuntu
  - name: ubuntu-16.04-ansible
    driver:
      provision_command: apt-get install -y init
      run_command: /sbin/init
      platform: ubuntu
  - name: ubuntu-14.04-ansible
    driver:
      platform: ubuntu
  - name: ubuntu-12.04-ansible
    driver:
      platform: ubuntu

  # Debian
  - name: debian-9-ansible
    driver:
      provision_command: apt-get install -y systemd
      run_command: /bin/systemd
      platform: debian
  - name: debian-8-ansible
    driver:
      run_command: /sbin/init
      platform: debian
  - name: debian-7-ansible
    driver:
      image: diodonfrost/debian-7-ansible
      platform: debian

  # Oraclelinux
  - name: oraclelinux-7-ansible
    driver:
      image: diodonfrost/oraclelinux-7-ansible
      run_command: /usr/sbin/init
      platform: centos
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd
  - name: oraclelinux-6-ansible
    driver:
      image: diodonfrost/oraclelinux-6-ansible
      run_command: /sbin/init
      platform: centos

  # Amazonlinux
  - name: amazonlinux-2-ansible
    driver:
      image: diodonfrost/amazonlinux-2-ansible
      run_command: /usr/sbin/init
      platform: centos
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
  - name: amazonlinux-1-ansible
    driver:
      image: diodonfrost/amazonlinux-1-ansible
      run_command: /sbin/init
      platform: centos

  # Gentoo
  - name: gentoo-stage3-ansible
    driver:
      image: diodonfrost/gentoo-stage3-ansible
      run_command: /usr/lib/systemd/systemd
      platform: gentoo
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd

# Define playbook
suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
